### ISSUE TITLE
Link Syver's Setup with SciML project

### ISSUE THREAD

**Issue by PabRod** [DEEPDIP-project/CoupledNODE.jl#1]
### Syver's implementation

Syver's code uses a `Setup` struct to define a boundary problem (see [here](https://agdestein.github.io/IncompressibleNavierStokes.jl/stable/generated/LidDrivenCavity2D/)). In a nutshell:

```julia
# Create the boundary conditions
u_bc(x, y, t) = y ≈ 1 ? T(1) : T(0)
v_bc(x, y, t) = T(0)
bc_type = (;
    u = (; x = (:dirichlet, :dirichlet), y = (:dirichlet, :dirichlet)),
    v = (; x = (:dirichlet, :dirichlet), y = (:dirichlet, :dirichlet)),
)

# Store them as a Setup object
setup = Setup(x, y; viscosity_model, u_bc, v_bc, bc_type);

# Pass the Setup as a parameter to the solver
pressure_solver = DirectPressureSolver(setup)
```

### SciML implementation

Simone's tutorials on SciML input the same information via `project`(see [here](https://github.com/DEEPDIP-project/NeuralNS-SciML-Tutorials/blob/c80d2ddfe1fccd131537a08fecc374238d3d7c4a/tutorials/NS_SciML_vs_direct.jl#L72))

## Goal

In order to allow communication between both implementations, we'd like to have a wrapper that translates Syver's solution into the SciML standard.

**Comment by SCiarella** [comment]
Closed by #47
