### ISSUE TITLE
Test data committed to repo

### ISSUE THREAD

**Issue by v1kko** [DEEPDIP-project/CoupledNODE.jl#116]
Currently the test data is commited to repo, which makes cloning slower.

I think we can generate the data on-the-fly for the tests, so that we do not have to store the data in the repo anymore.

**Comment by luisaforozco** [comment]
I also see that a trained model has been committed [here](https://github.com/DEEPDIP-project/CoupledNODE.jl/tree/main/simulations/NavierStokes_2D/outputs), we shouldn't be committing this kind of files to the repo.
