### ISSUE TITLE
Find a way to add NeuralClosure to Project.toml

### ISSUE THREAD

**Issue by v1kko** [DEEPDIP-project/CoupledNODE.jl#117]
We have a few options here:

1. Include NeuralClosure inside CoupledNode.jl
2. Make NeuralClosure independently available in the julia main repo
3. Adjust our actions to manually add NeuralClosure package

**Comment by luisaforozco** [comment]
Initially we were thinking that NeuralClosure would be only necessary for generating the data. Therefore, that script would be untested and CoupledNODE would consider that the data is generated (.jld2 files) and operate from there. 
In that sense, one would not need to have `NeuralClosure` available in the CI nor in the `Project.toml`.
Maybe I am missing something, do we need it somewhere else?

**Comment by v1kko** [comment]
That is interesting, and actually also links to issue #116 . If we solve this then that issues becomes much easier to solve.

- I think that CoupledNode should be able to generate the data, because that is the first thing that we (apparently) do when installing the package. Therefore I this functionality should be available.

- Also one could say that all scripts in a package should be executable after all Project.toml dependencies are installed. 

It is true that we do not need NeuralClosure for anything other than data generation, but because of the above reasons I feel it should be part of the package

**Comment by v1kko** [comment]
I have tried many things, the thing I found that works best is adding NC within the script itself, with a standalone repo of NC.

I think after this we should ask Syver to add NC to the public julia repo, that is the only way to add something to the Project.toml as dependency. I already made a cleaned up repo that can be used for this (that preserves history) https://github.com/DEEPDIP-project/NeuralClosure.jl
