### ISSUE TITLE
Make `create_f_CNODE` also return the NODE

### ISSUE THREAD

**Issue by SCiarella** [DEEPDIP-project/CoupledNODE.jl#36]
In this way there is no need for the user to call directly `NeuralODE(*)`.

Then, `create_f_CNODE` will need to receive as input also the parameters that will be used for the solution, like t_range, algorithm, ecc..

**Comment by luisaforozco** [comment]
If the force is needed, for example to create the loss, one could get it via: `my_neuralODE.model`

**Comment by luisaforozco** [comment]
This is implemented now in branch [wrap_neuralODE](https://github.com/DEEPDIP-project/CoupledNODE.jl/tree/wrap_neuralODE).

However, I see that there are some sort of memory leaks (many allocations) that were not there before. We need to first understand what is going on before merging that work.

**Comment by luisaforozco** [comment]
That PR was closed. The branch should also eventually be removed but I leave it in case we want to look back at something. I close this issue because this is no longer relevant, we changed completely the way of writting the forces.
