### ISSUE TITLE
Improve comments

### ISSUE THREAD

**Issue by SCiarella** [DEEPDIP-project/CoupledNODE.jl#7]
Suggestions by @luisaforozco :

- `CNODE` maybe explicitly mention what C stands for coupled.
- Like that you keep a single way of defining the initial values.
- Not clear the use of ; in some cases, it doesn't seem consistent.
- In example2_part2 when plotting `multi_GS.gif` put labels of the 3 rows or explain that they are 3 different examples (i.e. with different parameters).
- In example2_part2 the coarser grid is only for v, not for u?
- Loos MulDtO not clear can we add a link to resources explaining it?
- Homogenize notation to what Benjamin and CWI time uses?
- Make it clear/distinction between a priori and a posteriori loss/train/inference.
- I would like to have an outline of what is going to be done in the example. 
  For instance in example 2:
1. Definition of the problem: discretization, initial conditions, parameters.
2. Definition of elements of the equations: RHS, closure.
3. Burn-out to initialize closure model.
4. Generation of results.
And for example2_part2
1. Definition of the problem: discretization, initial conditions, parameters.
2. Definition of elements of the equations: RHS, closure (NO NN yet).
3. Burn-out to initialize closure model x2.
4. Define a coarser grid.
5. Get the solution for the coarser grid and compare with the solutions of the fine ones.

**Comment by luisaforozco** [comment]
We need to also:
- Check the import statements so that the dependency tree is clear for everyone.

**Comment by APJansen** [comment]
Also:
- make it more clear that the training data comes from a NeuralODE because it's the analogue of DNS

**Comment by SCiarella** [comment]
also:
* [ ] more clear names to the different examples
