### ISSUE TITLE
Structure as a Julia package

### ISSUE THREAD

**Issue by PabRod** [DEEPDIP-project/CoupledNODE.jl#8]
- [x] Structure this project as a basic package
- [x] Create docs
   - [x] Release them as website
- Add other desirable plugins, such as:
   - [x] Continuous integration 
   - [x] JuliaFormatter

Side effect: from PkgTemplates perspective I am the only author.

- [x] Extend the list of authors to fairly credit all contributors

**Comment by PabRod** [comment]
`PkgTemplates.jl` doesn't work with already existing code. More specifically, it **requires** an empty folder. My (suboptimal) workflow has been the following:

1. Create a new, homonymous project on an empty folder.
2. Manually copy-paste the folder structure and GitHub actions.

I strongly recommend starting all our future repositories directly from `PkgTemplates.jl`, so we can take advantage of its power.

This relates to our earlier conversation, @luisaforozco @SCiarella.

**Comment by PabRod** [comment]
Side effect: from `PkgTemplates` perspective I am the only author.

- [ ] Extend the list of authors to fairly credit all contributors

**Comment by APJansen** [comment]
I added and applied JuliaFormatter in PR #16, we could also add it in the CI, following something like [this](https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/main/.github/workflows/FormatCheck.yml). But since that won't cause conflicts with other changes, I wanted to get the first part done ASAP.

**Comment by PabRod** [comment]
Regarding releasing the docs as website, my two cents:

- I am not working on this. I was basically starting when the team reorganized
- It is substantial and independent enough to deserve its own issue
